In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df=pd.read_csv("/content/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.isnull()
df.dropna(inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
reg = linear_model.LinearRegression()

reg.fit(df[['area','bedrooms', 'age']], df['price'])

LinearRegression()

In [6]:
reg.coef_

array([  108.83858908, 26014.7106632 , -2977.4869961 ])

In [7]:
reg.intercept_

218391.98634590406

In [8]:
reg.predict([[3000, 4, 40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([529867.11638492])

In [9]:
112.06244194*3000 + 23388.88007794*4 -3231.71790863*40 + 221323.00186540437

521797.13165196433

In [10]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([579659.86671001])

In [ ]:
#example 2

In [23]:
pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5567 sha256=2d4a7e94bb63a16af7fad49066967805f4b42c02d2dc7836c8a13de1b75cd088
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [24]:
from word2number import w2n

In [13]:
df1=pd.read_csv("/content/hiring.csv")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [20]:
df1["test_score(out of 10)"] =df1["test_score(out of 10)"].fillna(df1["test_score(out of 10)"].median())
df1


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [21]:
df1["experience"]=df1["experience"].fillna("zero")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [25]:
df1['experience'] = df1['experience'].apply(w2n.word_to_num)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [27]:
reg=linear_model.LinearRegression()
reg.fit(df1[["experience","test_score(out of 10)","interview_score(out of 10)"]],df1["salary($)"])

LinearRegression()

In [28]:
reg.predict([[1,1.0,9]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([42243.08588064])

In [29]:
reg.predict([[12, 10, 10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [ ]:
#example 3

In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model

In [32]:
df3=pd.read_csv("/content/carprice.csv")
df3

Mileage  Age(yrs)  Sell Price($)
0     69000         6          18000
1     35000         3          34000
2     57000         5          26100
3     22500         2          40000
4     46000         4          31500
5     59000         5          26750
6     52000         5          32000
7     72000         6          19300
8     91000         8          12000
9     67000         6          22000
10    83000         7          18700
11    79000         7          19500
12    59000         5          26000
13    58780         4          27500
14    82450         7          19400
15    25400         3          35000
16    28000         2          35500
17    69000         5          19700
18    87600         8          12800
19    52000         5          28200

In [33]:
X=df3[["Mileage","Age(yrs)"]]
X

Mileage  Age(yrs)
0     69000         6
1     35000         3
2     57000         5
3     22500         2
4     46000         4
5     59000         5
6     52000         5
7     72000         6
8     91000         8
9     67000         6
10    83000         7
11    79000         7
12    59000         5
13    58780         4
14    82450         7
15    25400         3
16    28000         2
17    69000         5
18    87600         8
19    52000         5

In [34]:
Y=df3[["Sell Price($)"]]
Y

Sell Price($)
0           18000
1           34000
2           26100
3           40000
4           31500
5           26750
6           32000
7           19300
8           12000
9           22000
10          18700
11          19500
12          26000
13          27500
14          19400
15          35000
16          35500
17          19700
18          12800
19          28200

In [36]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [39]:
len(X_train),len(Y_train)

(16, 16)

In [40]:
len(X_test),len(Y_test)

(4, 4)

In [43]:
reg=linear_model.LinearRegression()
reg.fit(X_train,Y_train)

LinearRegression()

In [44]:
reg.score(X_test,Y_test)

0.8051976321473555

In [45]:
reg.predict(X_test)

array([[16065.66708797],
       [39173.04251396],
       [22357.47465116],
       [17561.77217267]])

In [47]:
Y_test

Sell Price($)
14          19400
15          35000
9           22000
11          19500